# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 671ccf1faf442efdb90e93d1f27be79ef6bf03317f0f44be50be962d54b12d962e0d60c697120f72411b11d4ef180bf5ecd6645429540b2eb0c602bb217f0856

test:
  secret_key_base: 310299dc833243380cbbcbd6eb962d9537ddd3f757219c83fb60ce04d14d14327bda60ad10f3a7802767211520722a161e02d305d76d3f8e509a09599dddeaf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
